In [1]:
# import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
# import data, split independent variables and dependent variables
dataset = pd.read_csv('dataset.csv')
x = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

In [5]:
dataset.head()

Report_Date   Beds  Total_LTC_Resident_Cases  Total_LTC_Resident_Deaths  \
0  2021-08-01  129.0                         1                          0   
1  2021-08-01   90.0                         5                          0   
2  2021-08-01  425.0                         0                          9   
3  2021-08-01  144.0                         1                          6   
4  2021-08-03  129.0                         1                          0   

   Total_LTC_HCW_Cases  1st_dose_staff_vac_rate  2nd_dose_staff_vac_rate  \
0                    1                     0.87                     0.84   
1                    7                     0.56                     0.51   
2                    0                     0.81                     0.73   
3                    0                     0.97                     0.95   
4                    1                     0.87                     0.84   

   phu_ACTIVE_CASES  phu_RESOLVED_CASES  phu_DEATHS  phu_TOTAL_CASES  \
0               152               21091         393            21243   
1               417              162179        3460           162596   
2               152               21091         393            21243   
3                85               17305         217            17390   
4               139               21125         393            21264   

   phu_CASE_FATALITY_RATE  phu_Daily_New_Cases  phu_1st_dose  phu_fully_vac  \
0                0.018500                   14      0.769336       0.662662   
1                0.021280                   40      0.787886       0.694052   
2                0.018500                   14      0.769336       0.662662   
3                0.012478                    5      0.842742       0.718034   
4                0.018482                    5      0.770308       0.667107   

   LTC_Mortality_Rate  
0            0.000000  
1            0.000000  
2            0.021176  
3            0.041667  
4            0.000000

In [6]:
print(x)
print(y)

[[1.29000000e+02 1.00000000e+00 0.00000000e+00 ... 1.40000000e+01
  7.69336423e-01 6.62661616e-01]
 [9.00000000e+01 5.00000000e+00 0.00000000e+00 ... 4.00000000e+01
  7.87885995e-01 6.94052344e-01]
 [4.25000000e+02 0.00000000e+00 9.00000000e+00 ... 1.40000000e+01
  7.69336423e-01 6.62661616e-01]
 ...
 [2.24000000e+02 1.00000000e+00 3.10000000e+01 ... 1.39100000e+03
  8.84772462e-01 8.45642479e-01]
 [2.00000000e+02 1.00000000e+00 1.00000000e+00 ... 1.39100000e+03
  8.84772462e-01 8.45642479e-01]
 [1.32000000e+02 0.00000000e+00 1.00000000e+00 ... 1.39100000e+03
  8.84772462e-01 8.45642479e-01]]
[0.         0.         0.02117647 ... 0.13839286 0.005      0.00757576]


In [7]:
# split train and test data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0 )

In [8]:
# training the multiple linear regression model on the training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [9]:
# Predicting the test set results
y_pred = regressor.predict(x_test)
np.set_printoptions(precision = 2) # set decimal to 2
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),axis = 1)) # reshape(# rows, # cols)
# compare the predicted result with y_test

[[ 6.55e-03  0.00e+00]
 [ 9.17e-03  0.00e+00]
 [ 9.86e-02  1.34e-01]
 [ 1.80e-02  0.00e+00]
 [ 5.67e-03  6.25e-03]
 [ 7.25e-02  6.88e-02]
 [ 8.46e-02  9.09e-02]
 [ 5.13e-03  0.00e+00]
 [ 7.22e-03  0.00e+00]
 [ 7.10e-03  0.00e+00]
 [ 1.82e-02  1.18e-02]
 [ 1.43e-02  0.00e+00]
 [ 3.95e-02  4.10e-02]
 [ 7.02e-04  0.00e+00]
 [-2.82e-02  2.31e-03]
 [ 9.74e-02  1.73e-01]
 [ 5.70e-03  1.11e-02]
 [ 6.34e-02  6.93e-02]
 [ 4.99e-02  4.13e-02]
 [ 1.01e-02  8.62e-03]
 [ 2.12e-02  9.90e-03]
 [ 2.71e-02  0.00e+00]
 [ 9.15e-03  6.25e-03]
 [ 1.90e-02  0.00e+00]
 [ 2.95e-01  2.46e-01]
 [ 5.20e-02  4.75e-02]
 [ 4.97e-02  6.93e-02]
 [ 1.91e-02  9.62e-03]
 [ 1.43e-02  0.00e+00]
 [ 9.49e-03  6.25e-03]
 [ 1.44e-02  0.00e+00]
 [ 9.88e-02  9.65e-02]
 [-4.06e-03  2.12e-02]
 [ 1.09e-02  0.00e+00]
 [-6.08e-03  0.00e+00]
 [ 4.41e-03  0.00e+00]
 [ 1.01e-01  1.34e-01]
 [ 2.18e-02  9.90e-03]
 [ 1.79e-01  2.42e-01]
 [ 9.41e-03  0.00e+00]
 [ 6.88e-03  0.00e+00]
 [ 2.50e-02  2.82e-02]
 [ 2.42e-02  2.67e-02]
 [ 1.90e-02

In [10]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8851780302975596

In [11]:
# Random Forest

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [13]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state=0)
regressor.fit(x_train,y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [14]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0.   0.  ]
 [0.   0.  ]
 [0.13 0.13]
 [0.   0.  ]
 [0.01 0.01]
 [0.07 0.07]
 [0.09 0.09]
 [0.   0.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.01 0.01]
 [0.   0.  ]
 [0.04 0.04]
 [0.   0.  ]
 [0.   0.  ]
 [0.17 0.17]
 [0.01 0.01]
 [0.07 0.07]
 [0.04 0.04]
 [0.01 0.01]
 [0.01 0.01]
 [0.   0.  ]
 [0.01 0.01]
 [0.   0.  ]
 [0.25 0.25]
 [0.05 0.05]
 [0.07 0.07]
 [0.01 0.01]
 [0.   0.  ]
 [0.01 0.01]
 [0.   0.  ]
 [0.1  0.1 ]
 [0.02 0.02]
 [0.   0.  ]
 [0.   0.  ]
 [0.   0.  ]
 [0.13 0.13]
 [0.01 0.01]
 [0.25 0.24]
 [0.   0.  ]
 [0.   0.  ]
 [0.03 0.03]
 [0.02 0.03]
 [0.   0.  ]
 [0.   0.  ]
 [0.04 0.04]
 [0.07 0.07]
 [0.19 0.19]
 [0.   0.  ]
 [0.   0.  ]
 [0.01 0.01]
 [0.   0.  ]
 [0.14 0.13]
 [0.01 0.01]
 [0.04 0.04]
 [0.01 0.01]
 [0.19 0.19]
 [0.01 0.01]
 [0.05 0.05]
 [0.01 0.01]
 [0.   0.  ]
 [0.06 0.05]
 [0.05 0.05]
 [0.01 0.01]
 [0.   0.  ]
 [0.   0.  ]
 [0.   0.01]
 [0.   0.  ]
 [0.01 0.01]
 [0.14 0.13]
 [0.07 0.07]
 [0.   0.  ]
 [0.06 0.06]
 [0.   0.  ]
 [0.05 0.05]
 [0.03 0.03]
 [0.   0.  ]

In [15]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9917329775853083

In [16]:
#SVR

In [18]:
dataset = pd.read_csv('dataset.csv')
x = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

In [19]:
y = y.reshape(len(y),1)

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [21]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_x.fit_transform(x_train)

sc_y = StandardScaler()
sc_y.fit_transform(y_train)

array([[-0.55],
       [-0.58],
       [ 1.17],
       ...,
       [-0.5 ],
       [-0.55],
       [ 2.74]])

In [22]:
x_train = sc_x.transform(x_train)
y_train = sc_y.transform(y_train)

In [23]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR()

In [24]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_x.transform(x_test)))
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[ 4.60e-03  0.00e+00]
 [ 4.76e-03  0.00e+00]
 [ 1.25e-01  1.34e-01]
 [ 6.26e-03  0.00e+00]
 [ 1.49e-02  6.25e-03]
 [ 6.49e-02  6.88e-02]
 [ 8.22e-02  9.09e-02]
 [-5.71e-03  0.00e+00]
 [ 7.60e-04  0.00e+00]
 [-6.17e-04  0.00e+00]
 [ 1.95e-02  1.18e-02]
 [ 6.68e-03  0.00e+00]
 [ 3.65e-02  4.10e-02]
 [ 2.50e-03  0.00e+00]
 [ 9.02e-03  2.31e-03]
 [ 1.71e-01  1.73e-01]
 [ 2.37e-02  1.11e-02]
 [ 7.40e-02  6.93e-02]
 [ 4.72e-02  4.13e-02]
 [ 1.11e-02  8.62e-03]
 [ 8.80e-03  9.90e-03]
 [ 9.27e-03  0.00e+00]
 [ 6.85e-03  6.25e-03]
 [ 7.75e-03  0.00e+00]
 [ 2.54e-01  2.46e-01]
 [ 5.53e-02  4.75e-02]
 [ 6.56e-02  6.93e-02]
 [ 1.59e-02  9.62e-03]
 [ 7.50e-03  0.00e+00]
 [ 6.45e-03  6.25e-03]
 [ 6.58e-03  0.00e+00]
 [ 8.86e-02  9.65e-02]
 [ 2.67e-02  2.12e-02]
 [ 6.18e-03  0.00e+00]
 [-7.44e-03  0.00e+00]
 [-5.81e-03  0.00e+00]
 [ 1.26e-01  1.34e-01]
 [ 9.63e-03  9.90e-03]
 [ 2.10e-01  2.42e-01]
 [-2.46e-03  0.00e+00]
 [ 4.43e-04  0.00e+00]
 [ 3.21e-02  2.82e-02]
 [ 2.19e-02  2.67e-02]
 [ 1.23e-03

In [25]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9767504698972732

### Next Step
1. for linear regression, to check assumptions of Linearity, Homoscedasticity, Independence, and Normality. Linear regression model must meet those assumptions
2. If assumptions were not met, try Ridge regression and Lasso regression
3. for random forest, handle overfitting issue, try use boosting method to increase dataset
4. Evaluate the models with root mean square error and mean absolute error
